### ISSUE TITLE
Conditions Not Saving (story #2275)

### ISSUE THREAD

**Issue by clwhiteh** [MapStory/mapstory-meta#1000]
The conditions are not saving within the style rules for the story listed below. I have tried logging out and logging back in, closing the browser, restarting the entire computer, and deleting and re-uploading the data to MapStory several times. I am not sure what the issue is. 

http://mapstory.org/maps/2275/#full

**Comment by jonpmarino** [comment]
Hi @clwhiteh, apologies for the super delayed response. The issue with saving edited styles is a known issue with the current MapStory composer. We are currently reconfiguring the whole composer in preparation for a Beta site launch this summer. As a result, the current issue on mapstory.org prototype won't be fixed in the near term. Thanks for reaching out. Would love to have your story be one of the first to be tested for success in MapStory beta soon...
