### ISSUE TITLE
Issue #942  Edit Saving Problems

### ISSUE THREAD

**Issue by jeneboe1** [MapStory/mapstory-meta#1002]
Hi,

My edits on this MapStory save when in edit-mode but to not transfer to the view mode.  I added a mask to the country labels.  Also, the labels repeat within a country and they disappear at a certain scale.  Can this be fixed?

Thank you,
Jason

**Comment by jonpmarino** [comment]
@jeneboe1 sorry for super delayed response. The issue with saving edited styles is a known issue. We're actively re-confinguring MapStory composer whole stock. A testing environment will go live this summer and we will invite you directly to be one of the first testers. Unfortunately the current issue in MapStory composer won't be fixed in the near time.
