### ISSUE TITLE
StoryLayer page layout refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1042]
Change the layout of the StoryLayer page to align with the one in the mockup.
![screen shot 2015-06-16 at 4 30 43 pm](https://cloud.githubusercontent.com/assets/4611843/8240207/f5089600-15ce-11e5-8e66-4e60c52c80b3.png)

**Comment by travislbrundage** [comment]
So I have quite a few questions/comments on this one - perhaps we can discuss in a call tomorrow, but I thought it would be good to have them written down.
1. What does 'use' do?
2. What does 'flag' do?
3. We have 'Category' in the top section, and then 'Topic' as well in the Meta. They're the same thing, I believe. I don't have a problem with it, but I just thought I'd point out the information is duplicated.
4. For the tags, I presume I should just list the first few, since I don't believe there is a limit to how many can be attached to a layer. I assume the 'add' button should probably spawn an [angular modal](https://angular-ui.github.io/bootstrap/#/modal) prompting them for keywords to add?
5. Thinking about that, all the tags look like buttons. Is that intentional? Are they supposed to do something?
6. What is 'Related'? It looks like a list of other StoryLayers, but how is this list determined?
7. How would one get to the viewer app from this page? I don't see an obvious connection in the mockup, but maybe I'm just missing something.
8. I assume those social media links appear only for if the user has them registered with MapStory? That is, if the user only has their twitter attached, the only text that appears will be 'message' and 'twitter'. On this note, I don't actually see the ability to attach social media to a user's profile at present. Is that what [Issue #582](https://github.com/MapStory/mapstory/issues/582) is about?
9. There's a little piece of text that just says 'comments' above the comments section. Is that intended to be there? I thought it might be a header, but just doesn't look like it in the mockup.

**Comment by reynalddizon** [comment]
> What does 'use' do?
> -Use StoryLayer to make a mapstory. So basically, this will link to the composer interface with this Storylayer added in the Storylayer tab.
> 
> What does 'flag' do?
> -Flag means you're marking the Storylayer because it has some issues content-wise. Ask Jon for clarification about this concept.
> 
> We have 'Category' in the top section, and then 'Topic' as well in the Meta. They're the same thing, I believe. I don't have a problem with it, but I just thought I'd point out the information is duplicated.
> -Yeah, they're pretty much the same. It's fine to duplicate. I think we'll go with the term "Topic" for both.
> 
> For the tags, I presume I should just list the first few, since I don't believe there is a limit to how many can be attached to a layer. I assume the 'add' button should probably spawn an angular modal prompting them for keywords to add?
> -yeah, that's okay. Maybe list a few tags, and  an indicator that there are more tags included. Like: apple, ball, cat, 5 more. +add
> 
> Thinking about that, all the tags look like buttons. Is that intentional? Are they supposed to do something?
> -in bootstrap, they're called badges. But yeah, clicking a tag would bring you to the search page populated with search results of that selected tag.
> 
> What is 'Related'? It looks like a list of other StoryLayers, but how is this list determined?
> -This is a big discussion. Let's talk about it on standup.
> 
> How would one get to the viewer app from this page? I don't see an obvious connection in the mockup, but maybe I'm just missing something.
> -in that iframe-looking interface on the left, there should be a button that should launch the full screen mode of the viewer app. See the current mapstory.org interface.
> 
> I assume those social media links appear only for if the user has them registered with MapStory? That is, if the user only has their twitter attached, the only text that appears will be 'message' and 'twitter'. On this note, I don't actually see the ability to attach social media to a user's profile at present. Is that what Issue #582 is about?
> -Not at present, but it's part of the mockup. My idea is to link accounts in the edit profile page. And use those to enable these social media sharing. This being said, please see Issue #1057 for the updated mockup.
> 
> There's a little piece of text that just says 'comments' above the comments section. Is that intended to be there? I thought it might be a header, but just doesn't look like it in the mockup.
> -yeah it's just a header, it would be nice if there's a counter for comments. Like: Comments (123)

**Comment by travislbrundage** [comment]
Awesome, thank you for the detailed response Rey!

**Comment by jonpmarino** [comment]
I think we should change "use" to "compose mapstory". Will cause that vertical bar to move a bit to make room.
