### ISSUE TITLE
Re-enable the time slider.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1055]
detail pages should have this: 
![screen shot 2015-06-19 at 3 04 45 pm](https://cloud.githubusercontent.com/assets/1141646/8260912/9698ec2a-1694-11e5-9e8b-bf2f63226bb4.png)

not this: 
![screen shot 2015-06-19 at 3 07 39 pm](https://cloud.githubusercontent.com/assets/1141646/8260966/f34c89c2-1694-11e5-9fcb-59cd657042de.png)

**Comment by reynalddizon** [comment]
For time slider controls (like pause, play and others), use the font-awesome characters. I think it's already included in the dev site, but here's the cheat sheet. 
http://fortawesome.github.io/Font-Awesome/3.2.1/cheatsheet/

**Comment by travislbrundage** [comment]
This is partially working right now. http://mapstory.beta.boundlessgeo.com/maps/133/viewer

The part I am most confused about is loading the nouislider.css. This might be due to my inexperience with bower... I see the file located in mapstory/static/vendor/nouislider/src, but I can't reference it there. I also see in the bower.json that 'nouislider' is listed as a dependency. However, I don't see any bower_components directory, nor another directory specified... so, the file exists but I am confused about how to implement it. It needs to be pulled in [viewer.html](https://github.com/MapStory/mapstory-geonode/blob/master/mapstory/templates/maps/viewer.html#L6).

**Comment by travislbrundage** [comment]
Apparently the change I made in [Pull Request #54](https://github.com/MapStory/mapstory-geonode/pull/54) didn't fix the nouislider css not appearing... because it can't find jquery.css to load either. I actually don't know where that file came from. Although I still believe it is the correct file to reference, it's not loaded into the static css files.

**Comment by travislbrundage** [comment]
Just going to note that although this isn't 100% completed, it's in a state where it at least works, but the styling isn't quite right. Ran into the issue I noted above.

**Comment by travislbrundage** [comment]
[Pull Request #61](https://github.com/MapStory/mapstory-geonode/pull/61) should finally fix that.

**Comment by garnertb** [comment]
The time slider has been re-enabled for the layer detail and map detail pages.  There are some performance issues that still need to be worked out (see related issue) as a medium priority task.
