### ISSUE TITLE
Header elements disappear when browser is minimized

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1075]
Need a mobile behavior that maintains header. Perhaps looks like this:
![45678](https://cloud.githubusercontent.com/assets/2573761/8287493/476659a2-18de-11e5-9c56-872cda329897.jpg)

**Comment by travislbrundage** [comment]
Working on this, I think what makes the most sense is for there to be a hamburger menu for the Explore, Create, and Journal items. I think in place of "How To" it may be better on mobile to just have additionally Get Started, Get Skills, and Get Involved (removing the dropdown). Since we have an outer "dropdown" affect with the hamburger it doesn't make sense to me to induce another. The user panel is already a dropdown so it should be fine as is.

Quick Search may just need to disappear altogether for mobile resolutions. I can have it appear as long as it fits, though.
