### ISSUE TITLE
Move Beta to Tomcat

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1084]
Jetty is not the final answer

**Comment by garnertb** [comment]
@davisc: When you do this, can you move the .geogitconfig (I think its in /var/www) file to tomcat's home as `/usr/share/tomcat7/.geogigconfig`?

```
chown tomcat7:tomcat7 /usr/share/tomcat7/.geogigconfig
chmod 775 /usr/share/tomcat7/.geogigconfig
```

**Comment by davisc** [comment]
Sure thing. Thanks for the note.

**Comment by davisc** [comment]
I did the following so that tomcat and jetty can run side by side:
- Reconfigured Jetty with Supervisor (ansible changes removed required files)
- Updated jetty config to listen on port 8082
- Installed tomcat and deployed the 2.6 war provided by @garnertb with the connector listing on port 8080.
- Updated the web.xml to configure DATA_DIR for Tomcat 
- Updated permissions so that Jetty and Tomcat owner:group were in sync (www-data)
- Updated nginx to route /geoserver to localhost:8080 and commented out the default route to Jetty listening on 8082
- Updated nginx to increase the proxy timeout (will add this change to the ansible config)
- Made the changes in the comment above from @garnertb with a minor change - chown tomcat7:www-data
- Stopped Jetty and Started Tomcat
