### ISSUE TITLE
Welcome modal for Composer

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1098]
<img width="878" alt="screen shot 2016-03-10 at 11 51 46 am" src="https://cloud.githubusercontent.com/assets/4611843/13677072/8f064366-e6b6-11e5-8890-1abdcad500e4.png">

**Comment by davisc** [comment]
Proposed Changes from Jon.

-Replace text "Welcome to StoryBoard" and "lorem ipsum..." with...

"Welcome to the MapStory Composer"

"Share your story of change in the world in four steps:"

-add some arrows between the 4 graphics so that user gets a sense its a 4 step process

-under the graphics change the words to:

First, select and style the StoryLayers you want to use in your mapstory

Second, break your mapstory up into different sections by creating StoryBoxes

Third, give your mapstory meaning and context by adding StoryPins with text, audio or video

Finally, preview your mapstory before you publish it for a global audience to enjoy!

-under the 4 steps we should 3 nice icons for "Take a tour" (hopscotch), "Start composing", or "Get more help" (links to Get Skills page)

**Comment by reynalddizon** [comment]
Please add a "Do not show this again" option

**Comment by Coop56** [comment]
@jonpmarino You said this existed at one point right?  This modal?  Any idea where the template file for that may be?

**Comment by Coop56** [comment]
@davisc or @travislbrundage Do you know where this old code lives?

**Comment by davisc** [comment]
@Coop56 https://github.com/MapStory/mapstory-geonode/blob/7e91d3d21bf39418417e270a273a881cc9e64672/mapstory/templates/maps/editor_tour.html

**Comment by Coop56** [comment]
Great thanks @davisc - planning to work on this after I get hopscotch working to a basic level.

**Comment by Coop56** [comment]
@davisc @reynalddizon @jonpmarino The welcome modal is live and working.  I'm sure there will be some CSS adjustments you want but this should close this issue.  If you have changes to make please ticket a new issue.  Let me know if you guys have any questions.

**Comment by reynalddizon** [comment]
@Coop56 how do you access the welcome modal?

**Comment by Coop56** [comment]
It pops up as soon as you go to Composer - it looks like it hasn't been pushed to demo yet.
