### ISSUE TITLE
Create Layer issues

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1241]
"CREATE" allows a user to initiate a new StoryLayer directly in the browser, even if they don't have data to upload. The current workflow starts from the "CREATE" tab accessible from the header drop-down. The user gives the StoryLayer a name, selects the type of geometry it will be made of, defines attributes, and creates new layer. At that point, the layer should be opened for crowd-editing (geogig) and the creator should create metadata
- [X] Enable user to create a two word feature rather than having _
- [X] Put Create StoryLayer into the same modal as Upload and Append are in now
- [X] Once created it should generate link for user
- [X] Address failure to Create New Layer
- [X] Make sure thumbnail is applied to new layer
- [ ] Make sure newly created layers spawn geogig / versioned editing repos

**Comment by davisc** [comment]
@davisc: I did a pull request for the layer create task. also made a fix to maploom and deployed and updated one. If you could get that in and try it on your end. To test: 1) goto /layers/create endpoint. 2) give it a layer name, add any attributes, click create 3) complete the wizard 4) when in maploom, drop points and set the “time” field. reinitializing the timeline server will get them all on the timeline with the tics. We’ll make it so that when a feature is saved at a time-tic not currently present, it reinitializes the time line.  this should be enough to get some feedback.

@smesdaghi: What should be the final step of the wizard? Step 3, save draft?

**Comment by jonpmarino** [comment]
Create Layer results in layer showing up as Administrator account. When I click to "edit" the layer in maploom I get an error (see screenshot below). If I X that error our and just try to add features anyway the Add form looks good with my fields, but I get an error message when saving (screenshot)
![3333](https://cloud.githubusercontent.com/assets/2573761/10919698/3f59f636-823a-11e5-973f-d50fa9294471.jpg)
![3311](https://cloud.githubusercontent.com/assets/2573761/10919705/45a8fa32-823a-11e5-8da1-d29729c84c75.jpg)
![88888](https://cloud.githubusercontent.com/assets/2573761/10919708/4b9a1750-823a-11e5-86b2-a657d869f5b6.jpg)

**Comment by jonpmarino** [comment]
Tyler taking on for next sprint.

**Comment by jonpmarino** [comment]
I get the following error when Creating new layer. It occurs no matter what type of Geometry I select
![9999](https://cloud.githubusercontent.com/assets/2573761/12055435/510d41ec-aefb-11e5-9161-fd68dd6aa8db.jpg)

**Comment by jonpmarino** [comment]
Once created, StoryLayer appears as "Administrator" account

**Comment by nittyjee** [comment]
So I created a storylayer, just with 3 points - everything's working fine, except there are no time controls, either in editing or viewing modes. Attached is a screenshot, for this layer (in case the problem disappears and reappears like it sometimes does magically):
http://mapstory.org/layers/geonode:nitin_trial_1
![no_time_controls](https://cloud.githubusercontent.com/assets/3781494/13276837/f2e30ade-da88-11e5-8d3d-349a30062bc1.png)

**Comment by jonpmarino** [comment]
I am closing this issue. The one remaining item is addressed in #1464
