### ISSUE TITLE
Responsive Homepage

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1348]
LG (desktop), MD (tablet-landscape), SM (tablet-portrait) and XS (phone)
### Navbar
- [x] For SM and XS screens, place all the menu items (Explore, How To and Journal) and Profile under the navicon (burger) menu.
- [x] "Create" menu option should be hidden for all mobile devices.
### Parallax/ Animated GIFs
- [x] For all mobile devices: Hide all animated GIFs except for Africa.gif (the topmost parallax image).
### "The atlas of change" (Orange) section
- [x] For all mobile devices: Hide "Upload StoryLayers" and "Compose MapStories" calls to action.
- [x] Improve the searchbar styling.
### Featured MapStories
- [x] For all: Center all the category tabs
- [x] For all mobile devices: Disable the carousel interface. 
- [x] For MD screen size: show 3 cards per row.
- [x] For SM screen size: show 2 cards per row. 
- [x] For XS screen size: show 1 card per row. 
### New "How-To" section
- [x] consolidate the following sections: Get Started, Get Involved, Get Skills, Thinkers and Thoughts, MapStory Projects.
- [x]  Column 1: 
  Title: Get Started.
  Subtitle: "MapStory is an open platform for organizing our knowledge about how the world changes over time and space. Click on a link to the right, and learn how you can start contributing observations of your own."
  Bullet list: Students, Educators, Humanitarians, Businesspeople, Librarians, Researchers, Policy Makers, Journalists.
- [x]  Column 2: 
  Title: Get Involved
  Subtitle: "Join with your neighbors, or collaborators on another continent, to launch initiatives, help others, write code and govern the mapstory.org platform. We’re a community, not a company."
  Bullet list: Community Initiatives, MapStory Projects, Thinkers and Thoughts. (I dont think they have standalone pages yet, so we just comment out/hide these sections instead of deleting them altogether. I need Jon's input on this)
- [x]  Column 3: 
  Title: Get Skills
  Subtitle: "MapStory is for everyone, not just web developers and GIS experts. We work hard to get you the help you need to improve and succeed."
  Bullet list: MapStory 101, MapStory Wiki, Help Center
### Footer
- [x] Keep all text and links

**Comment by nguyenist-zz** [comment]
Hey @jonpmarino @reynalddizon - I'm looking over the list above.

During weeknights / intermittent free hours here and there, I will start on smaller design items I can work on like:
- **Get Started Section**: `For desktop: Update the icons with nicer images with orange/brown/gray color scheme` 
- **The atlas of change" (Orange) section**: `Improve the searchbar styling.` 
- If you have any smaller design items, send them my way. It's easier for me to knock out when I have an hour here and there. 

During weekends, I will have longer blocks of time to: 
- read a bit more about best practices on how to best structure code for LG (desktop), MD (tablet-landscape), SM (tablet-portrait) and XS (phone)
- in general focus on actual frontend code / css
- ideally sync up with @travislbrundage on a strategy since he mentioned he wrote the code for the current website
- come up with a better idea of how I'd like to tackle the items above.

**Comment by Coop56** [comment]
Home page is responsive, closing.
