### ISSUE TITLE
Separate interests by comma, and make clickable so a storyteller search is spawned, based on interest filter

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1358]
Interests are currently clickable. But, the Search doesn't seem to populate all storytellers that list that Interest. @reynalddizon and I both have "policy" as an interest right now, as an example.

**Comment by travislbrundage** [comment]
What is wrong with the current way interests are being handled in the edit profile? Using it, they are separated by commas and not spaces. So I'm not sure what the issue is with that. The second part isn't there yet because there is currently no storyteller filtering, so it depends on implementing that at least partially.

**Comment by jj0hns0n** [comment]
There is nothing wrong, its just not very clear to the user what is going
on. The tokenization just makes things clearer from a UX perspective.

You should be able to use the API to filter by owner (aka storyteller).

**Comment by travislbrundage** [comment]
I believe this issue is finished and can be closed - correct me if I am wrong?

**Comment by jonpmarino** [comment]
confirmed and closing.
