### ISSUE TITLE
Animation for collapse/expand of sidebar

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1364]
- [x]  Add missing directional arrows
- [ ] Animation for collapse and expand

**Comment by Coop56** [comment]
The sidebar already is collapsible anywhere in the process I thought - did you notice somewhere that it's not?

**Comment by reynalddizon** [comment]
Both demo and beta don't have that collapse toggle for me, so i can't figure out how to minimize/expand the sidebar. Jon reported the same issue earlier.

**Comment by Coop56** [comment]
Oh that's right - because the font awesome icons aren't showing up.  Did you figure this out @davisc?  I can work on it if you don't have time, I'll just need access to the demo server setup.

**Comment by Coop56** [comment]
Ok the sidebar is collapsible in all places now and it's working on demo because we got the font awesome icons working.  I also fixed up the back buttons as that was a quick 10 minute change, so they are more specific now.  Commit sent to solve these two issues.  I'll get to animation after completing some other higher priority tasks.

**Comment by jonpmarino** [comment]
closing. this is complete.

**Comment by Coop56** [comment]
@jonpmarino The only thing not complete here is animation but that's fairly low priority I think.

**Comment by jonpmarino** [comment]
agreed. renaming and moving forward.

**Comment by Coop56** [comment]
No longer relevant, closing.
