### ISSUE TITLE
Basemaps in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1389]
- [x] Add header beneath "Add a StoryLayer" that says "Choose your basemap"
- [x] Make existing basemaps a drop down
- [x] Only allow one basemap to be visible at a time

**Comment by jonpmarino** [comment]
Took first item out of #1365 and made it its own issue. Rest of #1365 deals with playback functions in toolbar

**Comment by Coop56** [comment]
@jonpmarino - We made some real progress on this today thanks to a lot of help from @JWileczek.  There was a lot of work we had to do to actually differentiate between storyLayers and baseMaps.  The dropdown is now working as intended as far as only showing baseMaps.  Now I have to set it up so that the only baseMap set to visible is the one currently selected and then fix a bug where 2 of the 5 basemaps are still appearing in the storyLayers list for some reason.

I'll be working on that this weekend and Monday morning in preparation for the demo.

**Comment by Coop56** [comment]
@jonpmarino I just sent up a commit that gets this mostly working.  The commit is at https://github.com/MapStory/MapLoom/commit/a7ed2e51190718a9fa47e07fbad5064d861223e8.  The two bugs are the layer list itself is still showing 2 of the basemaps even though we wrote a function to filter those out and the fact that the dropdown menu does not by default select the default basemap that shows up on the map.  I'll work on debugging these, but the bulk of the functionality is there now for this issue.

Since OSM is not on demo yet - please move that task to a new ticket that includes bringing OSM to composer-wip branch and then setting it as the default.

**Comment by Coop56** [comment]
This task is complete, there is a known bug that I am ticketing in a new issue.

**Comment by davisc** [comment]
#1402
