### ISSUE TITLE
Organizations Requirements

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1400]
Organizations need some redesigning to match our concept for MapStory. A user should be able to be assigned as an admin/owner of an Organization page. This lets them perform admin functions on the Org page at the front-end level of the website, such as adding StoryLayers and MapStories to their page. Also, MapStory org pages have social links for Twitter and Facebook and a tab for Journal Articles that are written by Org pages admins. 

As per the mockup, the Org Page should have a summary, and Interests Tags. The "Send message" button can send a message to the Org Page admin user account.
- [x] Create Organization Page admin assignments
- [x] Social links for Twitter and Facebook
- [x] Journals
- [x] Interests Tags and Summary

**Comment by jj0hns0n** [comment]
@travislbrundage as discussed with Jon, we do NOT want to have organizations actually login (i.e. they should NOT act like a user account). We can add the social links for twitter and facebook to the group profile. For favorites, journals and messages, we need to find a way to associate these with the group.

**Comment by jj0hns0n** [comment]
@jonpmarino Can you confirm that we actually need a message inbox for organizations? Doesnt really seem necessary to me.

**Comment by jj0hns0n** [comment]
Also curious about the necessity of an organization favorites. How is this any different than just adding the resource to the organizations collection?

**Comment by jonpmarino** [comment]
Hi guys, given the new Collections model, we don't need to login as organization. Users will login as themselves and be able to administrate the org page they have admin rights to. @jj0hns0n correct? I don't think now that a message module for the organization is a priority since users can message the org page admin user. Perhaps as a future goal. Favorites is no longer necessary either, as long as the org page admin has a way to add content to their collection. An org page doesn't need to author journal articles as itself, but the org page admin should be able to add journal articles to its page that have been written by individual users.

**Comment by jj0hns0n** [comment]
This all sounds about right, lets discuss tomorrow. I think the only
outstanding thing here is to be able to add Journal articles to a
collection.

**Comment by travislbrundage** [comment]
Thanks for the corrections guys - updating the issue to reflect it. I had some misunderstandings about what the organizations were actually doing.

**Comment by travislbrundage** [comment]
Closed by https://github.com/MapStory/mapstory-geonode/pull/187
