### ISSUE TITLE
Explore Page Bugs

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1401]
- [x] Long titles overflow on the Explore page. Truncating and showing the full title on rollover is probably the best option.
  Test URL: http://mapstory.org/search/?q=Test&limit=100&offset=0&is_published
  Image:
  <img width="916" alt="screen shot 2015-10-16 at 2 09 21 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699851/6a0aa830-797f-11e5-88dd-e0ae3ae2c882.png">
- [x] Explore page shows "page 1 of NaN” before loading is complete
#### StoryLayers/Org Search Cards
- [x] Truncate Profile Info on StoryTeller cards
- [x] Two different scrolling methods are used for the whole Explore page and the available StoryLayers. Maybe merge into one and consider infinite scrolling? This is a small point.
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published
- [x] Using the quick search doesn't apply the result filter within explorer. On demo use the quick search to search for 'elephants' and observe the explore page results includes all results regardless of a text match

**Comment by travislbrundage** [comment]
"Long titles overflow on the Explore page. Truncating and showing the full title on rollover is probably the best option." Done, current default limit is 25 characters for truncating.

"Explore page shows "page 1 of NaN” before loading is complete" Should be done.

Fixed by [PR#221](https://github.com/MapStory/mapstory-geonode/pull/221)

"Make "blank" avatar consistent. Some users have default blue avatar, some users have broken image symbol as avatar. It looks like if users logged in with Google or Facebook their Avatar doesn't show in Search? See #1393" Removing this as #1393 covers the issue.

**Comment by jonpmarino** [comment]
We should also add to this issue that quick search is not generating results.

**Comment by Coop56** [comment]
These two commits fix the extra scroll bar and the quick search.  @jonpmarino 

https://github.com/MapStory/mapstory-geonode/commit/cd2f62d115cb697ccf0f1707dd200a0a38af0283

https://github.com/MapStory/mapstory-geonode/commit/9e9c3376961e97fae4d97b9abedf9ea656caa4a3
