### ISSUE TITLE
Uploader code base extension and debugging points

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory-meta#1416]
In the dev provisioning the uploader code is currently imported via python pip.  At run time things happen under celery scheduling. Both of these make it very hard to trace and identify sources of error or work out how to extend capabilities. There needs to be a way for contributers to work with the codebase:

1) how to debug what is happening at run time? 
2) can the code base be run from a local working copy of a git fork?
3) How to run unit tests on the importer?

**Comment by jj0hns0n** [comment]
@rob-metalinkage the instructions for running the tests are here
https://github.com/ProminentEdge/django-osgeo-importer

You can git clone this repo and pip install -e it into your active
virtualenv to to development.

**Comment by rob-metalinkage** [comment]
I tried this but wasnt sure how to test if it was working from within the context of a mapstory build

basic noob - does pip install -e  uninstall the previously installed version? 

AFAICT the instructions for provisioning will need to be updated to allow user option to do this on setup by editing the requirements.txt file. Is there an obvious way to control this choice closer to the other configuration options in scripts/provisioning/host_vars/vagrant.yml? Feels icky making little changes in lots of different places.

alternatively, I guess I could add another task in the ansible playbook to check if uploader working copy
is present as a peer module and force this?

IMHO  there is a missing step in the test instructions, if testing within this install method, which is to change directory to the uploader code base location after vagrant and run the tests there.

I'm presuming debugging is then a matter of hacking the uploader code to insert a pdb.set_trace() - and somehow during the celery processing it will give control to the console?

Which leaves the final question how to run a test of uploading a layer to the mapstory app.

I'll update the README in the mapstory-geonode to include all the necessary steps once I've tested them.

**Comment by garnertb** [comment]
@rob-metalinkage: I take the opposite approach than the one you're suggesting.  Instead of running importer tests in the mapstory VM, I run importer tests in the importer VM and mapstory tests in the mapstory VM.  This allows me to very quickly identify if the source of the problem is the core uploader or the mapstory build.  

Here is my workflow:
1) An import fails in mapstory.
2) Download the failed data.
3) Stand up the django-osgeo-importer using vagrant.
4) Add a test case for the failed upload in the importer tests, using the configuration options supplied at the time of upload.
5) If the test passes, the problem can be isolated to Mapstory.  If the test fails, fix the bug directly in the importer code base, add the data as a permanent test fixture and bump the version in mapstory-geonode.

I typically do not run importer tests in the mapstory build, although I can see why one may want to.  The Django test runner _should_ be able to facilitate that. 

Answers to your questions:
1) how to debug what is happening at run time? 
Use common python debug tools like ipdb; pdb or remote debugging with an IDE like pycharm.  You can force celery to run synchronously by setting `CELERY_ALWAYS_EAGER=True` in the settings.

2) can the code base be run from a local working copy of a git fork?
Yes, but I'd recommend using the vagrant box that comes with the importer.

3) How to run unit tests on the importer?
As @jj0hns0n follow the instructions here: https://github.com/ProminentEdge/django-osgeo-importer.

**Comment by rob-metalinkage** [comment]
Thanks for the tips. I think that makes sense in terms of the importer functionality - but I still need to get a handle on the extension points for the process within the MapStory space.
What I'd really like to test is the propagation of meaningful diagnostics back to the user in MapStory - and then when I have something working its going to be extracting/guessing additional metadata during upload, and getting user to verify or modify it. Maybe it wont be the importer per se - but a chain of processing of which the importer is the first step, but the basic pattern for this interaction and the testing would be the same.

**Comment by garnertb** [comment]
I'd recommend reading up on Django application conventions which expose plenty of extension points for you to inject this functionality if it has to be custom to mapstory.  The importer ships with custom handlers that developers can enable based on their specific application needs, implementing this as one of those handlers may also be a good option.
