### ISSUE TITLE
Force user to complete properties modal and "save" as first step in composing mapstory

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1449]
> clicking "compose mapstory" from any location (header, layer detail, or home page) first launches the welcome modal (take tour, compose mapstory)
> 
> clicking "compose mapstory" on the welcome modal should activate the Properties modal. User has to give their story a title and complete basic metadata before "Saving" and then being able to engage in the rest of composer.

**Comment by jonpmarino** [comment]
@davisc this is a front-end workflow, but may need to be thought through with what you're doing on styling persistence, returning to saved draft mapstories later, etc. Just flagging. Not sure.

**Comment by Coop56** [comment]
I changed the order of the workflow so that when you click Compose Mapstory it immediately brings up the Summary modal and dismisses the tour modal.  That should let the users know that they should fill out these forms and click save - but as of now they can still leave the summary modal without saving.  When you say force them to save - what would you like me to do?  Some sort of form validation that makes sure they fill out all of the forms (or a set of required ones) before they click Save?  What should happen if they click the X at the top of the modal?  @jonpmarino @reynalddizon

**Comment by jonpmarino** [comment]
Could we just remove the X, and also next to "save" add a button for "exit composer" that just takes user back to home?

**Comment by Coop56** [comment]
I pushed some changes - https://github.com/MapStory/MapLoom/commit/0396461a30d9c26479586635b638a93d69da8c82 - that should close out this ticket.  It changes the workflow a bit so that the user gets sent from the welcome modal into the summary modal if they click composer mapstory.  It also does form validation to ensure that they input a title before they are able to save.  @jonpmarino @reynalddizon We can change up what is shown to the user if the form is not valid, right now I just have it printing the word Required next to the Title label and disabling the Save button.

**Comment by Coop56** [comment]
@jonpmarino @reynalddizon This can be closed out right?

**Comment by jonpmarino** [comment]
yes. closing now.
