### ISSUE TITLE
Changing Name in Profile doesn't update Name in Card

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1457]
Changed username form MapStory Admin to Marco Polo. Still shows up as MapStory Admin on card.

![grabprofile](https://cloud.githubusercontent.com/assets/2573761/14534741/80b0da9a-0238-11e6-896c-0610ee1a0e4c.jpg)

**Comment by jj0hns0n** [comment]
Probably need to rebuild the index. I dont think its rebuilt on every save.

**Comment by travislbrundage** [comment]
Yeah, this is only going to change the Profile - so on user search, the name is updated there. I'm not sure if there is a way to link the profile saving to rebuilding the index for MapStories since it's a different object. I believe after a `rebuild_index` (or resaving that MapStory), it will update.

Should we just have the index rebuild every once in a while? Or maybe in the Profile save we can fire a signal to update all their owned MapStories/StoryLayers?
