### ISSUE TITLE
StoryLayer ordering in the sidebar doesn't reflect the layer stacking on the map display

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1509]
<img width="1280" alt="screen shot 2016-04-26 at 11 49 34 am" src="https://cloud.githubusercontent.com/assets/4611843/14825588/85b775c0-0ba8-11e6-8017-8fed631dbe9d.png">

in the example, lewis and clark (red line layer) is at the very bottom of the stack (in map display) even though it's on top of the orange polygons (states and territories layer) on the sidebar. It should be more like this: 

<img width="1280" alt="screen shot 2016-04-26 at 11 49 44 am" src="https://cloud.githubusercontent.com/assets/4611843/14825730/080c98d4-0ba9-11e6-8a01-b8c383704622.png">

(note the layer order in the sidebar.)

**Comment by JWileczek** [comment]
@reynalddizon I'm sorry Rey I completely misinterpreted the meaning of your issue here. You are talking about the ordering within the legend in comparison to the sidebar not the layer ordering itself in the map. When you say within the map display I thought you were talking about how layers stack on the map itself. This is a quick fix that I asked @Coop56 to make for me since I'm in the middle of changes for the draft, but it should be up soon.
