### ISSUE TITLE
Explore page CSS - content and user search

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1610]
<img width="1022" alt="screen shot 2016-06-06 at 1 07 31 pm" src="https://cloud.githubusercontent.com/assets/4611843/15830683/b89cdd4a-2be7-11e6-8289-8278d3c8d112.png">

---

<img width="1023" alt="screen shot 2016-06-07 at 10 54 50 am" src="https://cloud.githubusercontent.com/assets/4611843/15862650/5236796e-2c9e-11e6-8a58-49d0dff6ff9e.png">

---

Full list of filters:
<img width="1022" alt="screen shot 2016-06-06 at 1 07 51 pm" src="https://cloud.githubusercontent.com/assets/4611843/15830686/bd5deb58-2be7-11e6-8986-035ab67f202e.png">

**Comment by jonpmarino** [comment]
Hey @reynalddizon this looks really good. One thing we may want to add back somewhere in content is a place for trending tags, since @travislbrundage did the work to expose most used tags already. Also, we could eliminate "Editors Picks" since we sort of already provide for that with the featured content on HOME, which is set by an admin.

**Comment by glynnis** [comment]
Closing this. I think this will get addressed as we do the Explore redesign work.

If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
