### ISSUE TITLE
Re-Implement "Related" logic on layer and story detail pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1762]
In the long-run, a key strength of MapStory will be its ability to help viewers discover connections between layers and stories across a wide variety of dimensions (time, place, topic, etc).

In the short-run, we should re-implement 3 forms of "related" logic that existed on retro:

1. On the LAYER DETAIL page, a viewer should see a list of "mapstories that use this storylayer"

2. On the MAPSTORY DETAIL page, a viewer should see a list of "other popular mapstories in this category"

3. on the MAPSTORY DETAIL page, a viewer should see a list of "other popular mapstories by this storyteller"

The screenshot below shows how 2 and 3 were implemented on the MAPSTORY DETAIL page.

![picture1](https://cloud.githubusercontent.com/assets/2573761/21105762/0746041e-c051-11e6-9f7b-ad13c2025730.jpg)

**Comment by emilyashley** [comment]
@jonpmarino as its written currently, the layer detail page does have a related content prepared if the resource is categorized, but it is commented out. 

The way it is set up is if a resource is categorized, there will be related content from that same category. It was hidden from view in the last rendition of detail page reforms because we had yet to discuss overarching mechanisms for finding related content and was seeking feedback on management / display / explorability designs for our content's detail pages.

I'd prefer to have a plan for the page as a whole and how layer & story explorability would differ before moving forward with this - do we have a design epic yet for the layer or story detail pages we can tie this into, @glynnis?

**Comment by jonpmarino** [comment]
@emilyashley makes sense to want to think about the bigger picture of explorability from layer and story detail pages. Probably also in conjunction with the epic on Explore/Search in general, since these things interconnect. Explore/Search is a #1 priority for me for post 0.0, along with @glynnis redesign interfaces for composer, editor and viewer. fwiw.

**Comment by jonpmarino** [comment]
Closing. Addressed in Roadmap where we can have a proper scoping discussion before breaking up into tickets.
