### ISSUE TITLE
interval mode doesn't work

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#184]
For example: http://mapstory.dev.opengeo.org/maps/14

**Comment by mpriour** [comment]
The big error that was causing problems was fixed in the TimeManager add in but never properly pushed to geonode.

I fixed that & updated the demo server

However, upon further inspection, the interval that you set with the slider doesn't matter and the range is always equal to the playback step size (ie. 1 year step = a 1 year range interval, no matter what you do to the range slider)

**Comment by mpriour** [comment]
Fixed in https://github.com/opengeo/gxp/commit/42b1a353a9eadbfb18843ff1c5866b00062eccba
