### ISSUE TITLE
persist geoserver configuration for date/time options dialog

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#191]
As Ian pointed out in an email dated 03/01:

the date and time options dialog on data page

The save button does not appear to do anything on the date and time options dialog during upload.  An endpoint to persist geoserver configuration would be needed and possibly one for the viewer config.

**Comment by cholmes** [comment]
Not sure what this is talking about, closing, we can reopen a new ticket that describes the problem more specifically.

**Comment by ischneider** [comment]
On a layer page, if you click the 'gear' button, a date/time options dialog pops up. This would be an ideal place to allow the owner of the data to configure and save the presentation style - currently only possible during upload and in geoserver admin.

At one point, this dialog had a save button on it that did nothing - at least that is gone now.

**Comment by ischneider** [comment]
See also #194

**Comment by cholmes** [comment]
What do you mean by 'presentation style'? And what are the options for geoserver?

**Comment by cholmes** [comment]
Also I'm not sure if the 'gear' button is the best, since that's also there on maps, not just layers. And it sounds like this is settings for layers? 

If that assumption is right then I think the logical place wouldn't be in the gear on the time slider, but on the layer page, maybe in a 'settings' tab?

**Comment by ischneider** [comment]
'presentation style' refers to how geoserver reports the time dimension extent in WMS capabilities. If it's set to 'LIST' each unique value from the dataset will be returned. This is good for 'event' data like earthquakes. If the 'INTERVAL' style is chosen, an interval must be specified and this is returned along with the first and last date of the dataset. There is a 'CONTINUOUS' option that we don't do - it's basically INTERVAL with a computed interval.

Interval style is the most appropriate playback style for many layers even if they have 'event' data. There is a significant payload difference, too especially if the data actually _is_ interval in nature. One disadvantage of using interval - you lose some details up front (all of the unique event dates).

I thing having this in a settings tab makes sense.

**Comment by cholmes** [comment]
This is just for the defaults of the layer?

The 'gear' does override this for the map, right? Like when you select interval? 

But this would be the default that people making new maps would get? And then they could choose to switch it?

**Comment by ischneider** [comment]
Right, just the layer defaults being discussed here.

The map playback settings don't exactly override so much as represent something new - a request with an instant on a layer with interval data or an interval request on a layer with event data.

**Comment by ischneider** [comment]
And yes, the default would be the initial option in the new map and the user could switch it (except that if the layer is marked interval, one cannot get LIST behavior in the sense that the viewer will only know about the start/end/interval (and not all the specific times).

**Comment by cholmes** [comment]
Cool, makes sense.

So for the layer, an alternative to the 'settings' tab could theoretically be to just persist what the owner sets with the gear. But I think the 'settings' tab makes things clearer.

Another thing that would be good to set there is the base layer. So that the owner can set the background to what he wants others to see.

Settings might also be a good place to add in more data, like we're talking about with imagery. Could just be a link to the uploader, or even a little place where they could upload there.

Probably should have settings only appear to the owner of the layer (or the admin).

I can make a ticket for this.

**Comment by cholmes** [comment]
Would this also be a place where they could perhaps change the time column? Or like adjust the time parsing thing they set up? And even just being able to see what's that set to could be nice.
