### ISSUE TITLE
Timeslider stuck between intervals

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#199]
Computer: Windows XP 32-bit, Windows 7 Pro 64-bit, and Ubuntu 11.10 32-bit VM
Browser: Mozilla Firefox 10.0.2

Steps:
-Click "Search Stories" button under Mapstories category on homepage (http://mapstory.dev.opengeo.org/maps/search)
-Select a mapstory
-Go to view page of mapstory by clicking "View or edit this map" under the "Manage" category on right hand side
-Press the play button on the timeline -- timeline should correctly proceed through defined time animation intervals
-Expand time controller window
-Under the "Layers" dropdown within the time controller window, select/turn-on the layer
-Press the reset to the start button on the timeline
-Press the play button on the timeline -- error occurs: timeline will start correctly, then at some point will get caught between two sequential intervals (ie, moves from year 1918 to 1925 back to 1918, etc). Sometimes after moving a few times back and forth between two intervals, the timeline is able to move past the section, but may get caught up in a different interval later.

**Comment by bartvde** [comment]
The issue is that the timeline is occasionally calling setTime on the playback toolbar, but it should not do that. The issue here is that the Simile addOnScrollListener also runs when the timeline is moved programmatically, not only by user interaction. I have got a flag _silent on the timeline to prevent this, but apparently this is not working all the time.

**Comment by bartvde** [comment]
Should be fixed by using @mpriour new playing flag as is done here: https://github.com/opengeo/gxp/commit/31fb5047f52be1833e45a5d9100fe65503ecf41d
