### ISSUE TITLE
Map Properties don't seem to persist

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#214]
I'm psyched on the map properties options, but they don't seem to persist. I changed the background color and the zoom, and played some with the dateline wrapping. They changed my active map, and I was sure to hit 'save' on that map, but then when i went to the map page, or reloaded the full screen map, it was back to the defaults.

**Comment by ischneider** [comment]
A similar issue on http://mapstory.dev.opengeo.org/maps/54
The full page has the time options persisted, the small map does not. Additionally, the time properties dialog on the small page is odd-looking.

**Comment by vhamer** [comment]
Have had a similar issue here: http://mapstory.dev.opengeo.org/maps/107/view
The start time for the map does not save/persist. This is weird because when we made this map as a duplicate, the original had a different start date, and we have not adjusted the start date. It seems to have 'moved' to 1961 mysteriously. In trying to adjust it back to an earlier date, discovered that it won't save/persist.

**Comment by mpriour** [comment]
This is now fixed

**Comment by cholmes** [comment]
Matt fixed the issue that everyone else in this ticket was talking about, but was unaware of the functionality I was talking about. Assigning to Bart.

**Comment by bartvde** [comment]
Should be fixed with https://github.com/opengeo/gxp/commit/02f5d67f8cba08ef81f9912bd55c86c01a398e34

Not yet pushed to the dev server.

**Comment by bartvde** [comment]
Pushed to the dev server, will only work after re-saving a map.
