### ISSUE TITLE
No google earth api key assigned

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#222]
If I go to the google earth button I get the prompt that there's no google earth api key set for dev.mapstory.opengeo.org We should set one, or remove the google earth button.

**Comment by bartvde** [comment]
Hey Chris, Google recently removed the need for api keys for GE so Andreas updated GXP yesterday to account for this. I've just pulled this into MapStory and it works on my system (I had to reinstall the GE plugin since something was messed up with it even in the GE demo page). If it does not work, go to: http://www.google.com/earth/explore/products/plugin.html and see what plugin version you have, you need at least 6.x.

See also:

https://github.com/opengeo/suite/issues/42
