### ISSUE TITLE
International Dateline 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#227]
question from tucker: 

International Date Line:  http://mapstory.dev.opengeo.org/maps/new?layer=geonode:SPEEDING.  When I went to full screen on this one, then panned to the right, I noticed that we don't support wrapping across the international date line.  Is this anywhere in anyone's roadmap?

**Comment by bartvde** [comment]
This is a map property which can be changed by the user, but it's default value is off (to allow zooming out to the whole world). So just go to the map properties dialog (most left button in the map's toolbar) and check wrap dateline.

**Comment by bartvde** [comment]
Actually changing the projection to WGS84 will not give you both wrapDateLine and zooming out to the extent of the world in the full-screen map viewer. You will have the same limitations (these are mostly because OpenLayers has some issues with vector layers on a map that wraps the dateline and shows more than one world at a time, and it would require significant amount of effort to get this fixed).

The only relatively easy way to get this behavior would be to limit the map viewer to a fixed width and height, where width and height are a multiple of 256 pixels, so not a map viewer that fills the screen like it does now.

**Comment by bartvde** [comment]
I am closing this ticket since it's not yet clear what the desired action is. We should create a new ticket when it's clear what needs to be done.
