### ISSUE TITLE
Weird Behavior by Time Status Bar

### ISSUE THREAD

**Issue by ChristopherTucker** [MapStory/mapstory-meta#242]
http://mapstory.dev.opengeo.org/maps/84

I don't even know how to describe this.  The looping doesn't even work.  The timeslider doesn't register dates while the Titanic track data is moving.  This is really strange.  I normally write good bug reports, but I don't even know how to describe this.

**Comment by mpriour** [comment]
This problem is caused by the fact that the data set starts in 1909 with a single data point and then all the other data points occur over a few days in 1912. Thus without specifying the playback range to something smaller than original full range, the logic which automatically figures out the best time resolution and display format is going to give you answers which are not useful for this map.

I'm marking this as closed since this is really a data or user education problem and not a bug.
