### ISSUE TITLE
Wireframes for Thumbnails in Search results

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#26]
related to ticket #12

**Comment by dwins** [comment]
Comment from Chris: It would be nice to have a never-ending scrollbar (Google Reader-style) instead of paging controls for the search results

**Comment by ischneider** [comment]
Should I be focusing on actual wireframes or technical details? I thought the former were being done by spatialdev and co. Work is being done on the technical details:
https://docs.google.com/a/opengeo.org/document/d/1O92pr-jmOD0Fnd5ULKPzc0v3q4_n9popAvtVV04Wbuc/edit?hl=en_US

**Comment by ischneider** [comment]
Never ending scrolling proof of concept also completed though challenges exist here with paging model if results are to show both layers and maps - mixing results from two QuerySet objects. What is the sort order (by date)? Instead of the client providing a single count number to facilitate paging, the client will have to track map and layer counts separately and provide these on refresh requests. (if that makes sense)

**Comment by scrollie** [comment]
For reference, here are some speculative search wireframes from ~April: https://img.skitch.com/20111107-8mgrm9u7rmm37xdnbphmubppcp.png

Ian, we should probably arrange a call to talk through what needs to change on the above? Also, I assume the author/owner will be defining the thumbnail? We can probably insert that workflow into map info dialog (abstract, title, etc) and probably have a sensible default. 

Also, I know Ian's uploader work touched on this, but we should refine the metadata workflow as it occurs in two different ways: a messy form on upload that's accessible from the info page; an Ext dialog that accessible from the composer.
