### ISSUE TITLE
layout feedback for edit mode

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#292]
some suggestions for improving the layout of the full screen edit mode. you probably know many of them but thought i would list them out. 
1. remove scale on right hand side
2. change zoom controls from old open layers slider to the (+) and (-) on the info pages
3. make the gray time controls the full length of the map.

**Comment by bartvde** [comment]
I'll work on these, I think I am less swamped than Matt currently, should be straight forward.

**Comment by bartvde** [comment]
See:

https://github.com/opengeo/geonode/commit/8dc5b2635fb320a245de26f317497cec2b9ea160
https://github.com/opengeo/geonode/commit/bd8abde711287481a939e2eb34b9467c614c7939

for the first 2 items.

Third one is causing me a bit of trouble because of the nested toolbars. Maybe Matt has a quicker idea on how to accomplish this one.

**Comment by mpriour** [comment]
feedback #3 is not easily accomplished at this time due to the nesting of toolbars.
However, the bottom toolbar can & should be removed and then it will be fairly simple to make the toolbar the full width of the map.
I'll work on that part.

**Comment by bartvde** [comment]
#1 and #2 were done, #3 still needs to be done

**Comment by cholmes** [comment]
Closing this, as most of these are done, and I think item 3 here may have gotten done too with latest buttonology work.
