### ISSUE TITLE
Profile page doesn't properly recognize uploaded avatar

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#309]
After I've uploaded my avatar, it still says, "You haven't uploaded an avatar yet. Please upload one now." underneath my picture.

**Comment by bartvde** [comment]
I can confirm that the uploaded avatar is not used immediately everywhere.

**Comment by cholmes** [comment]
Confirmed this, and it's a lot more important with #447 as it prevents any user from showing up in search, since it's a required field.

**Comment by ischneider** [comment]
I've fixed the computation of incompleteness but there are bug(s) in our avatar module w/ respect to caching. Probably haven't been encountered before since caching is typically disabled in geonode (but is active in mapstory for many other uses)

**Comment by ischneider** [comment]
@cholmes Can you take a look at this again? I created a new user, saw the profile invalid. Added avatar. Updated first name, last name and blurb and it was 'complete'. Due to search result caching, it might take 1 minute to see results.

I saw some oddness in avatar related to caching but now cannot duplicate.

**Comment by cholmes** [comment]
It's perfect. Great work. Ready for production.

**Comment by cholmes** [comment]
Looks like this was pushed? Just tested on mapstory.org and worked great.
