### ISSUE TITLE
order of selecting layers

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#328]
when you click new map, it seems that whatever layer you add first will designate the earliest start time for playback, even if the second layer you add has earlier dates.

**Comment by bartvde** [comment]
@elasher any example of 2 layers that exhibit this behavior?

**Comment by ghost** [comment]
if you create a new story,

then select Civil War Battles, click add
then select Civil War State Alignment, click add

click done.

If you select in reverse order, same steps, you get this:
http://mapstory.dev.opengeo.org/maps/166

**Comment by mpriour** [comment]
I hit play on that map & everything looks fine.
I was wondering what the specific issue is that you were worried about?
Matt Priour

On Wed, Apr 11, 2012 at 2:20 PM, elasher <
reply@reply.github.com

> wrote:
> 
> if you create a new story,
> 
> then select Civil War Battles, click add
> then select Civil War State Alignment, click add
> 
> click done.
> 
> If you select in reverse order, same steps, you get this:
> http://mapstory.dev.opengeo.org/maps/166
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/328#issuecomment-5075307

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
@mpriour that map is fine because the sequence of layers is (top to bottom): civil war battles and civil war state alignment.

If @elasher adds the layers in the reverse sequence, the playback only starts at 1861 but it should start at 1857.

**Comment by mpriour** [comment]
This is by design. But I think it is perfectly valid to modify that design.
Currently, the playback range is only changed by new layers that have a more restrictive playback range. This is to prevent an issue where you have one or more "background" time data sequences which cover a large span of time expanding the playback well beyond the time range of interest for the time data sequences one is actually interested in.
One can manually modify this behavior by choosing a wider playback range using the Playback Options settings.
I am very open to any suggestions about how to modify this logic or the UI for directly specifying the playback range option.

**Comment by mpriour** [comment]
@elasher, @sampepple should feel free to start this discussion on the dev-mapstory@opengeo.org mailing list. We are open to suggestions.

**Comment by cholmes** [comment]
Moving to medium term. Hopefully we redo time slider stuff in the medium term, and should be sure to take this in to account.
