### ISSUE TITLE
annotations dialog date formatting too restrictive

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#366]
I cannot enter negative (BCE) dates. In general, it would be nice to not have to specify the full date as per ISO8601.

**Comment by mpriour** [comment]
ISO8601 date formats weren't required before, but no matter what format you used you could not get a BCE date to parse. This was largely due to the fact that the native Date.parse function in javascript doesn't handle negative years (or at least I could never find a format in which it both parsed the negative year AND kept it negative)

I've provided a fix in:
https://github.com/opengeo/gxp/commit/c9e2d01da5f946a7bfc036b93996250b8ce7f0f5

This provides the user the ability to put the BCE date in just about any reasonable format as long as you **ZERO PAD THE YEAR** to 4+ digits or more, such as:
- Aug -0501
- 8 -0501
- 08/15/-0501
- -0501/08/15
- -0501-08-15

If you don't zero pad **OR** if you have a date with a negative year greater than 4 digits (ie. -50100) then it will just use the year and ignore the rest. There should definitely be some kind of user facing notice about this. I tried to provide a useful invalidText message in a QuickTip that explained this on non-parseable dates but its display is suppressed.
