### ISSUE TITLE
Can't add annotation to BC map

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#378]
1. http://mapstory.dev.opengeo.org/maps/187/view
2. Notes > Add Note > Point
3. Placed point on Map
4. Title: Test Point (or something like that) | Description: I am a point
5. Couldn't select date from calendar, so entered:
   Start time: March 02, -501
   End time: March 20, -500
6. Checked: Include in Timeline, Include in Map., Position: Top right
7. Saved. 

Point stayed on map, annotation did not show on timeline or map.  If I have the wrong format for the start and end dates, it shouldn't successfully save.  There should be some feedback for the user.

Note also, that when I tried to edit the point and press save -- everything froze. https://skitch.com/alyssawright/8h5de/note-freeze

**Comment by mpriour** [comment]
See #366
You have the date in the wrong format (you didn't zero pad to 4 digits). However, it will still take just the year portion of it if you don't zero pad. Unfortunately, that become Jan 1 of that year and the animation doesn't cover that time frame.

The user SHOULD be informed of this and I have some language that should be shown to the user, but currently is not.
I need fix that so that the user IS shown a proper warning when the date format is questionable / incorrect.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/commit/898c930da09b9ac850a31c16a12d55d2cc308957 I think it's better for now to show a validation error to the user if the BCE year is not zero-padded.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/geonode/commit/8fd96457fa86cc278b431ef2c0d98c25364674ac

**Comment by bartvde** [comment]
But also, if you have saved a BCE date such as -0978-03-01 and then go back and edit the point, you're back at an invalid date since the 0 has disappeared. So this needs a bit more work.

**Comment by bartvde** [comment]
I am sure this can be done more elegant, but this works: https://github.com/opengeo/gxp/commit/c8b3fe0c02d478acfa0c4e7b9cbe3522656e9800

**Comment by bartvde** [comment]
Tested on dev: you now get error message if you did not specify trailing 0. Also verified that using a trailing zero you can add BC annotations okay. Closing.
