### ISSUE TITLE
Nicer minimized buttons for layers and timeline

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#556]
Right now we have these small buttons to expand the timeline and the layer manager. And they take up lots of screen real estate, since they use a whole bar instead of a small button.

One way to make them nicer would be to use the style that the LMN salamati gxp editor uses, see http://rogue.geohub.opengeo.org:8080/salamati/ (hit 'close' on the 'tools' bar, and it should do a nice animated minimize to a 'Tools' tab). 

So ideally we have 'layers' on the left like the tools on salamati. And then on the bottom we have 'timeline' in a similar style. This should show more of the map and also explain to users what those buttons will do.

**Comment by iwillig** [comment]
This is going to be very hard to  do from within the ext.js framework. In fact almost impossible. I spent some time last week looking into how to make this happen. I think in order to actually make the panels work in a way that matches the above functionality we would need to use something other then ext.js panels. 

The main issue seems to be there is no good way to hide the panel when it is min mode. I tried messing around with the css and that did not seems to help. I can explain in detail if need be but the main issue is the ordering of the panels themselves. 

I am willing to look into this more but it seems like there are really only two good options here. One is to use something other then ext.js to do the timeline panel or to hack ext until it works how we need it. Both options seem like they could be time consuming. 

Chris do you have any thoughts on this?

**Comment by iwillig** [comment]
@cholmes Can you find the code for the salamati app.

**Comment by cholmes** [comment]
Hit limits with this, and other tickets have some other approaches, like #687. So closing this one.
