### ISSUE TITLE
Timeline view shows more information than map

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#65]
Maybe nothing, but there seem to be many points in the timeline and not many points in the animation for this map: http://mapstory.demo.opengeo.org/maps/20/view

Here's a screenshot of what we were seeing at the Nov 21 demo. https://skitch.com/alyssawright/gk8ni/fullscreen

**Comment by mpriour** [comment]
What you are seeing on the map is the exact snapshot in time 1390, where as the timeline is displaying somewhere between 25-100% the data for a map layer (100% in this example)

Since the map layer is displayed in normal or "snapshot" mode and not cumulative or ranged-playback mode, then you are seeing exactly what you would expect on the map. In this example, that is the 2 data points for the year 1390
