### ISSUE TITLE
daily notification emails not going out

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#663]
a cron is in place but it calls a non-existent management command

**Comment by ischneider** [comment]
To Test:
Need to set delivery preference accordingly (in profile page)
Do some commenting and stuff.
Currently daily sending is triggered at 00:00UTC on dev.
The last day of activity should be sent.

**Comment by cholmes** [comment]
@ischneider I tried to test this a couple times and it didn't seem to work. I believe I tested on both prod and dev, though I think more on prod because I think this got pushed. Will do two more tests right now.

**Comment by cholmes** [comment]
Tested on prod and it works there. So marking 'ready to deploy'. I think I saw something that said you deployed it to prod. Am testing again now, but I think tested before.

**Comment by cholmes** [comment]
Hrm, I'm confused by my last comment. It was working on _dev_, not on production. Confirmed to not work on production. Though I just tried to test again to be absolutely sure (though I'm 95% sure I tested 4 days ago, I have archive of a daily summary from dev, but from prod). But testing on prod I just hit #468 So that one was definitely working 4 days ago, not sure what happened.

**Comment by ischneider** [comment]
This should be fixed on production.

**Comment by cholmes** [comment]
Cool, I put some things to notify in, should find out later tonight if this is working for sure.

**Comment by cholmes** [comment]
Worked! Just got my daily email. Thanks Ian.
