### ISSUE TITLE
Add ability to embed video and links to Resources pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#678]
Screenshots attached. Want the ability to add You Tube video embeds and simple hyperlink text to Resources For pages. Just those two elements, in a standard design across the Resources For pages.

![slide1](https://f.cloud.github.com/assets/2573761/468007/36fe1302-b689-11e2-8c67-eef55b8752d4.jpg)

**Comment by emloux** [comment]
@jonpmarino Do you want the media ribbon and mapstories and users on this as well or not?

**Comment by emloux** [comment]
Related to #463

**Comment by jonpmarino** [comment]
@emloux I think the media ribbon and links look good as they are and will suffice. Only other thing that would be to have a right-hand box where we could pull MapStories created by folks in these categories...so you'd have some examplar MapStories created 'by educators', 'by journalists', etc. to give those audiences a glimpse of what they're peers have done

**Comment by DanielJDufour** [comment]
Embedding MapStories does not work.

**Comment by ischneider** [comment]
As for embedding MapStories in the 'links' this was not considered while designing the page - they were expected to be just links. This will require some thought about where to place them.

Another thought - instead of requiring pasting of embed code, what if we provide a 'shortcut' for an embedded map. For example (and drawing from wikipedia):

>  [[Map:id|width=800|height=600]

Replace 'id' with the map number. Other options added with the 'pipe' symbol.

**Comment by jonpmarino** [comment]
@ischneider this sounds good. Simple enough. Also, a more pertinent issue is that media in the media ribbons does not line up properly. See, http://mapstory.org/mapstory/resource/business/

**Comment by ischneider** [comment]
Closing - this seems covered by `getpages`
