### ISSUE TITLE
'save as copy' action in map editor not obvious

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#710]
The URL for the page does not change, but the map in the editor is changed to the new copy.

**Comment by cholmes** [comment]
I was actually just thinking about this. If we want to make copying obvious one spot we could put it is in the same place we put 'edit map' if you own a map. Like if you are just looking at a map then we could put 'copy map' next to 'view full screen' and it would take you to the map editor and by default have 'save' be to a new copy.

Right now I'm inclined to hold off though because it's possible to edit someone's SLD quite easily when you copy. Like the default action of changing the style would also change the original style. You can do this with creating a mapstory from a layer already. I'll make a bug for it on its own. But it's mitigated now with the less good 'copy' UI.

**Comment by cholmes** [comment]
#715 is the bug for what I commented on above.

**Comment by ischneider** [comment]
Closing - will be using new platform
