### ISSUE TITLE
Shared logins for mapstory.org and wiki.mapstory.org

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#736]
This will enable shared logins for mapstory.org and wiki.mapstory.org. OAuth may be the way to do this but does not need to be.

**Comment by cholmes** [comment]
From Jeff, it looks like some work was done on this:

http://mapstory.dev.opengeo.org/oauth2/access_token/ ... but doesnt
look like it is on prod.

**Comment by drwelby** [comment]
I've looked into this, and it seems like everything is there on the Django end to set this up. I would just need django admin access on the dev machine and a login for wherever the wiki is hosted.

**Comment by drwelby** [comment]
Remember that these GitHub issues are public, so don't post access details here.

**Comment by jonpmarino** [comment]
@drwelby right on. Thanks for catch.

**Comment by drwelby** [comment]
We're close to this working except for one catch - the OAuth2 library we're using doesn't like the query-style urls (index.php?title=Main_Page) that we're using in Mediawiki. So there's two options:

1) patch the OAuth2 library to pass and append query strings.
2) switch Mediawiki to use "short urls" instead of query string urls, so http://wiki.mapstory.org/index.php?title=Main_Page would become http://wiki.mapstory.org/wiki/Main_Page

If we do the latter, we should wait until we have #888 implemented so we can swap the urls easily. I think they look better so I'm leaning towards this. Thoughts, @ischneider @jonpmarino ?

**Comment by ischneider** [comment]
Agreed that the implications of 2 (at least on mapstory) are better - no patching, better looking URLs.

**Comment by drwelby** [comment]
The switch has been made, and all looks good except it broke the main logo image. @jonpmarino can you email me the wiki login? marc dot pfister at gmail

**Comment by jonpmarino** [comment]
@drwelby sure. Sending momentarily.

**Comment by drwelby** [comment]
This is ready for testing (technically it's already deployed).

**Comment by emloux** [comment]
Verified, closing
