### ISSUE TITLE
Storyteller/profile refresh

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#742]
The set of pages to view and edit one's profile is a bit of a mess. There are many different spots to change things, and it's not intuitive. We should have a nice redesign of all the various things to edit and display.

**Comment by cholmes** [comment]
Starting with assigning to Steven, as some design thinking and wireframes on this would be great. Can post them at https://github.com/MapStory/mapstory-roadmap/blob/master/items/storytellers.md which is the related roadmap item for this issue.

**Comment by jonpmarino** [comment]
Some running notes for this -
- a good design template are the profile pages at http://learni.st/users/tilley.brandon
- new profile page should separate users 'expertise' into searchable tags so that I can 'search' for a StoryTeller with specific skillsets. Expertise can be categories we are using for MapStories and org pages to keep things consistent. 
- We should explore implementing the capacity to host GeoBadges on a MapStoryteller's profile consistent with the http://openbadges.org/ framework
- Need a process for indicating that a MapStoryteller is a member of the Technical community and need to incorporate that filter into http://mapstory.org/storytellers/search (see below)
  -We should create an ability for a MapStoryteller to create a 'personal atlas'. this would involve selecting the Search functions (categories, time periods, storytellers, etc.) that interest them and they want to follow...the versioned StoryLayers they are contributing to as well. These will accrue into a continuously populated feed. User could also set 'email' notifications for how much from their Atlas they want pushed to their email. The profile view would then have 2 tabs..."profile view" and "atlas view". When a registered user logs in to MapStory, by default they should be taken to their atlas view. Link lineage could be http://mapstory.org/profiles/jonpmarino/atlas
  -need some link back to the profile as it appears to the public in the 'edit profile' viewer. ideally the edit profile viewer would be some kind of wysiwyg editor so a viewer could see the public view of his/her profile as edits are being done.

**Comment by jonpmarino** [comment]
@reynalddizon redesign accomplishes these ideas
