### ISSUE TITLE
Can't set users on org pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#767]
So we have this nice organization mapstories/storylayers/storytellers/storylayers used by widget at the bottom of org pages.

But there's no way to set it. Even in the admin page for the org (like at http://mapstory.dev.opengeo.org/admin/mapstory/org/89/) there is a list of users but you can only add users, and it seems to start populated by every user. 

At the very least we need a better way to set the users. For the first step it's fine if it's only in the admin page.

Next step would be have it as an 'edit' link on the org page, just like all the other options one can set on the org page. Then people don't have to go to the admin to do that one thing. 

It doesn't have to be elegant, just a way to add usernames from the site, so that they and their maps/stories show up in the widget.

**Comment by ischneider** [comment]
Not sure how possible (I think any org would be able to edit any other) or usable (the builtin pick-lists are horrible...) it will be to do via the admin page.

The current list is just random, IIRC

**Comment by cholmes** [comment]
Definitely is slightly preferable to do it via the org page itself.

**Comment by ischneider** [comment]
As per the comment on #768, we could use favorites to manage users, too.

**Comment by cholmes** [comment]
Yeah, that sounds good. I'd say to start favorited users should not have their maps/layers show up on the org page. The org owner will have to manually favorite the layers/maps they want. Later we can see about some nicer interface for it, but this should get us the control we need in the short term.

**Comment by ischneider** [comment]
There are two ways to handle 'favorite' users - one is make Orgs the only 'users' capable of having other favorite users. The other approach is to allow any user to mark favorite users. Technically, there's not a huge difference except to prohibit 'normal' users from having other favorite users would be more work. For the moment, I'm using the approach that any user (Org or normal) can select favorite users, the only difference being that the Org's favorites (users or otherwise) will be visible to others (via the tabs at the bottom of the org page) and a normal users favorites will be private (at least for the moment - we could expose these via the profile page).

**Comment by cholmes** [comment]
I think that approach sounds great. No reason to do the additional work so that users are prohibited from favoriting other users. I don't think we should expose the user's favorites anywhere though, unless people start asking for it. 

I guess eventually favoriting might be like 'following' on other systems, but let's cross that bridge later.
