### ISSUE TITLE
add 'feature info' in full screen view on layer/map page

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#790]
In the 'editor' view, the circle-i info looking button asks for login.

**Comment by cholmes** [comment]
I'm of two minds of this. First is that this is important, as feature info is a fairly core thing. Second is that few people will actually hit this, since we only really expose the 'view' (map composer) screen to logged in users.

Though this does make me think it'd be good to have select feature in at least the full screen view.

**Comment by ischneider** [comment]
Good point on edit vs view. Changing the title to reflect this.

**Comment by ischneider** [comment]
Reassigned to @bartvde
