### ISSUE TITLE
enable manage annotations button and give msg that map should be saved first

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#861]
Currently when the map is not saved, the manage annotations button is disabled. This is not clear to users. So instead, enable the button and give a message to first save if the button is pressed before the map has been saved.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/geonode/commit/826fbafd5383abd2dd730fcae17ce26659316366

**Comment by sshyu** [comment]
Thanks, @bartvde.  Can you let me know when this is available on dev (or another server, if that's quicker) for me to review?

**Comment by bartvde** [comment]
deployed just now on dev, so ready for testing @sshyu

**Comment by sshyu** [comment]
Thanks @bartvde--looks good.

Can we make the following updates?
- Title: Annotations
- Text: In order to add annotations, please save your map first by clicking the "Save Map" `(save map icon)` button.

Would be great to include an image of the save map button if possible in the text (as indicated above).

(Would have added more specifics earlier, but I didn't know you were ready to work on it yet. :))

**Comment by bartvde** [comment]
sure can do, will let you know when this is done

**Comment by bartvde** [comment]
done see: https://github.com/opengeo/geonode/commit/0cc35d7183ec7011d5a6e724b70ef02a8b7caee4 also deployed on dev

**Comment by sshyu** [comment]
Thanks @bartvde.  Just one little change and we should be good (didn't realize the icon would cause the text to wrap like it does).  Change the text to:

```
In order to add annotations, please save your map first by clicking the "Save Map" button:
{save map icon}
```

**Comment by bartvde** [comment]
done with: https://github.com/opengeo/geonode/commit/55061689f07de6624b336cd3bf992c2aa1cbce77

**Comment by bartvde** [comment]
deployed on dev

**Comment by sshyu** [comment]
Thanks, looks good!  Now just need to remove the period that's below the icon. :)

**Comment by bartvde** [comment]
done

**Comment by sshyu** [comment]
Thanks!  Message is good now.

In testing, I discovered another issue--can open another ticket for it but want to see if you can reproduce:
- I click the "Annotations" button on an unsaved map
- I see the warning message normally
- I close it
- I click the "Annotations" button again
- I see the warning message, but the width of the dialog box is much smaller in width (about ~100px instead of the normal width)

(Encountered using Chrome on OS X)

**Comment by bartvde** [comment]
Can reproduce, will look into it

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/e0c7630812867754f938d9a7713047bccef923ec
deployed as well

**Comment by sshyu** [comment]
Thanks, Bart!  The bug in my previous comment appears to be fixed on dev now.  (Chrome/OS X.)

**Comment by emloux** [comment]
Looks Great! Marking ready for deploy
