### ISSUE TITLE
loading a saved map is failing

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#87]
E.g. http://localhost:8000/maps/10

container is undefined
http://localhost:8081/script/@gxp.js/plugins/Tool.js
Line 356

var component = container.add(config);

**Comment by bartvde** [comment]
It seems to be looking for "layertree"

**Comment by samplecartography** [comment]
I think that my problem is similar. When I open a map I created a few days back => maps/24/view
the map will load with the saved extent and scale but only the base will show, no actual theme will
show up; I will then have to add the layer again to be able to see it or have the playback controls appear.

**Comment by mpriour** [comment]
I'm almost 100% positive that this is due to the problem I am experiencing
as well. It has nothing (that I can tell) to do with the controls/tools,
but rather with the layer source getting mangled when the map data is
returned by the geonode django app. Ian & Dwins could not reproduce it, so
I think it must have something to do with the way that we are running
things locally.

I have a gist showing the response differences:
https://gist.github.com/1374684

If you look at that, you can see that the JSON sent to save the map has the
temporal layer source as local.
I've checked and it is stored as local, but when the saved map data is
requested, the temporal layer(s) get new source definitions and something
somehow goes wrong in the reading/parsing of the capabilities response.
When I intervene and force the source as 'local' or force it to be a 'lazy'
layer (ie gxp doesn't even request the capabilities doc and just trusts the
layer definition), then it loads fine.

I thought I was the only one with this problem, so I was just working
around it, however, now it looks like we should investigate what exactly is
happening.

I am running local Mapstory dev server as follows:
- geoserver and geonetwork served from war's via tomcat on port 8080
- geonode-client is served in debug mode via ringo on port 9000
- mapstory django served in development mode (monitor/reload) via paster on
  9090
- local postgis databases for layers and for mapstory

On Sat, Dec 10, 2011 at 9:21 PM, samplecartography <
reply@reply.github.com

> wrote:
> 
> I think that my problem is similar. When I open a map I created a few days
> back => maps/24/view
> the map will load with the saved extent and scale but only the base will
> show, no actual theme will
> show up; I will then have to add the layer again to be able to see it or
> have the playback controls appear.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/87#issuecomment-3095427

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by mpriour** [comment]
I pushed a very temporary fix to this in the GeoNodePy maps/views.py view for the map_detail page. This deletes the tools parameter from the saved map config and lets it refill with the default tool config.

@ahocevar & I determined that a much better fix would be to have user embedded maps (maps/X/embed) and the embedded map on the map preview page (maps/X) share the same logic and push that all to the client side as much as possible. Currently the embedded maps don't work anyway so this is as good a time as any to go ahead and fix both of these problems at once.

**Comment by mpriour** [comment]
I do not recall trying to replicate this issue.  What are the steps to
reproduce it? Just make a map with layers on it?

## 

David Winslow
OpenGeo - http://opengeo.org/

**Comment by samplecartography** [comment]
mpriour,
to replicate the issue simply create a new map, add data, save map, and then try to view/edit map.
When I try to do this now, the base will show up and the add data button will be clickable, but when
clicked it it does nothing.

**Comment by mpriour** [comment]
samplecartography:
That is actually the same problem I have and I have to intervene using
javascript to modify the server response as described above.
This problem occurs in the maps/XX/view page

The problem Bart was reporting was a separate but valid issue, with the
preview map initialization failing after the base layers were loaded due
to inappropriate tools attempting to load. That problem has a temporary fix
which was pushed on Monday. I would like to more completely fix the issue
and make the embedded map function work again.

On Wed, Dec 14, 2011 at 10:10 AM, samplecartography <
reply@reply.github.com

> wrote:
> 
> mpriour,
> to replicate the issue simply create a new map, add data, save map, and
> then try to view/edit map.
> When I try to do this now, the base will show up and the add data button
> will be clickable, but when
> clicked it it does nothing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/87#issuecomment-3142793

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
Works for me now. Closing.
