### ISSUE TITLE
wrong year displayed on playback toolbar (time slider)

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#871]
This came up in: http://help.mapstory.org/question/171/why-is-wrong-year-displayed-on-the-time-slider/ and needs further investigation

**Comment by bartvde** [comment]
The relevant code is getThumbText in TimeSlider

**Comment by bartvde** [comment]
Dimension values in the map are:

```
["1991-01-01T00:00:00.000Z", "1992-01-01T00:00:00.000Z", "1993-01-01T00:00:00.000Z", "1994-01-01T00:00:00.000Z", "1995-01-01T00:00:00.000Z", "1996-01-01T00:00:00.000Z", "1997-01-01T00:00:00.000Z", "1999-01-01T00:00:00.000Z", "2002-01-01T00:00:00.000Z", "2003-01-01T00:00:00.000Z", "2004-01-01T00:00:00.000Z", "2006-01-01T00:00:00.000Z", "2008-01-01T00:00:00.000Z", "2011-01-01T00:00:00.000Z"]
```

**Comment by bartvde** [comment]
Can't reproduce

**Comment by ischneider** [comment]
This might be because you're at UTC+2 while us on the other side of the pond are UTC-X. So if the date is rendered in 'local' browser time, adding the offset for you will always result in some time on the same day while we always get a few hours the day before (which rolls the year back, too).

I'll see if I can hack at the getThumbText and fix it but otherwise you might be able to duplicate if you set your system timezone to a negative offset. Here's also a way to do it in firefox:
http://kb.mozillazine.org/Time_and_time_zone_settings

**Comment by bartvde** [comment]
good point @ischneider

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/bfae081297cb889157c40a82f665f198b728d9fc pulled in with: https://github.com/opengeo/geonode/commit/052b497c79afaf616eedf06fc82959371c7fd928
