### ISSUE TITLE
annotation for first frame does not show up

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#880]
might be related to timezone again

See also: http://help.mapstory.org/question/214/annotation-not-showing-for-the-first-year/

**Comment by bartvde** [comment]
Comparison is on the integer values, not on the date objects so this is strange

**Comment by bartvde** [comment]
Failing to reproduce, even after changing my timezone settings.

@ischneider @emloux are you guys able to reproduce Daniel's issue (see forum link for details)?

**Comment by bartvde** [comment]
It seems setCenterDate is not called in the small viewer, hence the annotations do not show up

**Comment by bartvde** [comment]
Additionally it also seems to depend on the timing of the load of the annotations store

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/469e38e2501ed36afecb619e70990ec98a6cff69 pulled in with: https://github.com/opengeo/geonode/commit/b87777314ec71cd7c4d5ffccbf49739d63aa1fb6

**Comment by DanielJDufour** [comment]
I tested the update on dev and the annotations do correctly appear on the first "frame," but they continue to appear after their end time.  MapStory URL is http://mapstory.dev.opengeo.org/maps/412/view/
ScreenShot:
![anopersistprob](https://f.cloud.github.com/assets/4313463/978444/de074c3a-06bc-11e3-85e6-0e9fe8007f25.png)

**Comment by bartvde** [comment]
@DanielJDufour what happens here is that because the annotation is not ranged (since end time = start time) we take a margin around the time to have a higher chance for it to show up (if the times are discrete in the playblack). Maybe we shouldn't do this at all, but this will mean that unranged annotations only show up if the playback time exactly matches the annotation's time. What's your take on this?

```
               var diff = (startTime-compare);
                        var percentage = Math.abs((diff/startTime)*100);
                        // we need to take a margin for the feature to have a chance to show up
                        if (percentage <= 0.1) {
                            this.displayTooltip(record);
                        } else {
                            this.hideTooltip(record);
                        }
```

**Comment by bartvde** [comment]
Alternatively my margin detection could be improved I guess, will look into it. I guess it's better to compare with the playback range instead.

**Comment by bartvde** [comment]
I've tried to improve the matching logic in: https://github.com/opengeo/gxp/commit/fbf4e878d0c004e8bf6ef51691a751f35d7874f2 the compare value might require some tweaking though

**Comment by bartvde** [comment]
pulled in with: https://github.com/opengeo/geonode/commit/c488def6d4e7912623970b7c59808a72734cf2fa

**Comment by bartvde** [comment]
it seems the value is still too high for your map

**Comment by bartvde** [comment]
lowered the value to 0.001, can you test this out @DanielJDufour ? I've tested this on your referenced map but it might make sense to test in other maps as well if possible.

**Comment by DanielJDufour** [comment]
Okay.  Works on the referenced map.  However, I uploaded a shapefile on dev that includes two identical polygons/features.  The first features has start and end times of 1995-11-24 and 1995-11-24 (the same).  The second feature has it's start and end time one day later on 1995-11-25.  The annotations with these same dates (set using the "now button) do not appear.  I imagine it's because of the discrete vs. ranged issue at hand, because when I range the start-time for the first feature by changing it's start year to 1994 (and keeping it's month and day), it appears.  Here's the mapstory and screenshot after this alteration:

![image](https://f.cloud.github.com/assets/4313463/1075144/65c15152-14c8-11e3-82b3-3900817802e0.png)

I'm sorry I can' t be very much help recommending a compare value, because I don't fundamentally understand why we need to do it this way.  It feels counter-intuitive.  I would recommend just doing it if it's a perfect match (for discrete times).  MapStory users are almost always aware of the exact times of the features, so I think they're willing to make the annotations line up exactly with the features' times.  I think it should all be synced up and handle discrete times (the playback, the features and the annotations).  I'm absolutely sure there's something technical I don't understand, but this is my recommendation.

**Comment by bartvde** [comment]
Thanks for your recommendation @DanielJDufour I'll get rid of the compare value completely and only work with exact matches tomorrow.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/532665899f2e917fd0c1bcbacbcdd8f524f49a7a pulled in with: https://github.com/opengeo/geonode/commit/56e23a9290e53c4891022adabe2dd3ea821d7886

This only shows non-ranged annotations for exact matches (date + time).
