### ISSUE TITLE
Make the text area in the content column in bulk upload resizable

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#952]
![grab8](https://f.cloud.github.com/assets/2573761/1364731/04a8a208-3845-11e3-9921-2cb324cab38c.jpg)

**Comment by bartvde** [comment]
This doesn't seem like a simple change unfortunately, because of the use of a textarea in combination with the row editor extension.

I can set grow: true on the textarea which will make it grow in the vertical direction, but the row editor won't grow along.
Also I can move the splitbar on the column to make the textarea bigger in the horizontal direction, but the other items from the row editor (date editor) are not moved along.

**Comment by jonpmarino** [comment]
@bartvde thanks for investigating. If there's one of these moves you can make easily that you feel good about, know what Daniel Dufour's underlying issue was, I say go ahead.
